
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db:3306/lifusic
    username: ENC(opq8CStgemkllGaDNVtL4pHsg8cuDRxQ)
    password: ENC(1Dm57XikhApWY0zpFOEEPkPWZtpqb72Y)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    root: info
    web: info
    sql: error # error: Display when error occur
    org.hibernate: error
    org.springframework: error
    com.chung.lifusic.core: info

host:
  server:
    account:
      http://account-server:8080